- block:
  - name: Create .scripts directory
    file:
      path: "~/.scripts"
      state: directory
      mode: 0755
      owner: "{{ username }}"
      group: "{{ username }}"  

  - name: Copy keyboard backlight
    copy:
      src: kbdbacklight
      dest: "~/.scripts/kbdbacklight"
      mode: 0755
      owner: "{{ username }}"
      group: "{{ username }}"
  become: True
  become_user: "{{ username }}"
