- block:
  - name: Remove virtualbox-guest-utils-nox
    pacman:
      name: virtualbox-guest-utils-nox
      state: absent

  - name: Install virtualization software
    pacman:
      name: "{{ software_virtualization }}"

  - name: Load virtualbox modules
    blockinfile:
      path: "/etc/modules-load.d/virtualbox.conf"
      marker: "# {mark} ANSIBLE MANAGED BLOCK"
      create: yes
      block: |
        vboxguest
        vboxsf
        vboxvideo
  when: software_virtualization is defined
  become: True

- block:
  - name: Check if Docker is installed
    shell: pacman -Qi docker
    register: docker_status
    ignore_errors: True

  - name: Enable Docker
    shell: systemctl enable docker && systemctl start docker
    when: docker_status is success

  - name: Add user to Docker group
    shell: usermod -aG docker {{ username }}
  become: True