---
- name: Check packages for updates
  shell: "pacman -Qu | wc -l"
  register: updates
  become: True

- name: Update packages
  shell: "pacman -Syu --noconfirm"
  when: updates.stdout|int > 0
  become: True
