- name: Create aur directory
  file:
    path: ~/.aur
    state: directory
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"
  become: True
  become_user: "{{ username }}"

- include_tasks: aur-packages-install.yaml
  with_items: "{{ aur_packages }}"
  loop_control:
    loop_var: item
